WEBUI-783: handle error folder upload
nuxeo/nuxeo-elements pull request #572
Opened 2022-08-03 11:04 UTC by SnehalNaik-DEV

2022-08-04 06:48 UTC, rakeshkumar1019 approved these changes, later dismissed
looks good

2022-08-04 08:26 UTC, GuruprasadAnk1996 approved these changes, later dismissed
Looks good !!

2022-08-04 08:27 UTC, richardsd requested changes
Nice work 💪

2022-08-04 08:27 UTC, richardsd commented on ui/i18n/messages.json
> +  "foderUpload.error": "Folder upload is not supported",
You have a typo in the key, it should be `folderUpload.error` instead.

2022-08-04 08:27 UTC, richardsd commented on ui/widgets/nuxeo-uploader-behavior.js
> +      } else {
Since the `_drop` method was not previously returning anything, I don't think you need this else condition.

2022-08-04 08:27 UTC, richardsd commented on ui/widgets/nuxeo-uploader-behavior.js
> +          this.notify({ message: this.i18n('foderUpload.error') });
So, if we have multiple folders we will perform the notify several times, which doesn't seem very useful. What do you think about storing this check in a local variable, and then issue the notify later if at least one directory was found?

```js
    const allFiles = e.dataTransfer.items;
    const files = [];
    let hasFolder = false;
    if (allFiles.length > 0) {
      for (let i = 0; i < allFiles.length; i++) {
        if (allFiles[i].webkitGetAsEntry().isDirectory) {
          hasFolder = true;
        } else {
          files.push(e.dataTransfer.files[i]);
        }
      }
     if (hasFolder) {
        this.notify({ message: this.i18n('folderUpload.error') });
     }
```

2022-08-04 08:27 UTC, richardsd commented on ui/widgets/nuxeo-uploader-behavior.js
> +          this.notify({ message: this.i18n('foderUpload.error') });
Up to discussion about this ofc. Thank you.

2022-08-04 08:27 UTC, richardsd commented on ui/widgets/nuxeo-uploader-behavior.js
> +          this.notify({ message: this.i18n('foderUpload.error') });
And don't forget to update the key to `folderUpload.error`.

2022-08-04 08:51 UTC, swarnadipa-dev approved these changes, later dismissed

2022-08-04 12:18 UTC, GuruprasadAnk1996 approved these changes, later dismissed

2022-08-04 12:33 UTC, rakeshkumar1019 approved these changes, later dismissed

2022-08-04 13:26 UTC, swarnadipa-dev submitted a review, later dismissed

2022-08-08 08:58 UTC, richardsd submitted a review, later dismissed
Looks good to me 👍

2022-08-08 15:04 UTC, semisse approved these changes, later dismissed

2022-08-09 07:56 UTC, GuruprasadAnk1996 submitted a review, later dismissed

2022-08-09 08:12 UTC, rakeshkumar1019 approved these changes, later dismissed

2022-08-10 05:31 UTC, rakeshkumar1019 submitted a review, later dismissed

2022-08-10 05:33 UTC, swarnadipa-dev approved these changes, later dismissed

2022-08-10 05:34 UTC, GuruprasadAnk1996 approved these changes, later dismissed

2022-08-10 08:11 UTC, richardsd approved these changes, later dismissed

2022-08-10 08:46 UTC, semisse commented on ui/widgets/nuxeo-uploader-behavior.js
> +    }
Please consider this change:
```suggestion
    const allFiles = e.dataTransfer.items;
    if (allFiles.length > 0) {
      const files = [];
      let hasFolder = false;
      for (let i = 0; i < allFiles.length; i++) {
        if (allFiles[i].webkitGetAsEntry().isDirectory) {
          hasFolder = true;
        } else {
          files.push(e.dataTransfer.files[i]);
        }
      }
      if (files.length > 0) {
        this.uploadFiles(files);
      }
      if (hasFolder) {
        this.notify({ message: this.i18n('folderUpload.error') });
      }
    }
```
This way we can keep the variable close to its usage principle.

2022-08-10 10:55 UTC, semisse approved these changes

2022-08-10 11:00 UTC, rakeshkumar1019 approved these changes

2022-08-10 13:30 UTC, richardsd approved these changes
Nice work 💪

2022-08-12 05:44 UTC, merged