ELEMENTS-1503: add workflow_dispatch in main workflow
nuxeo/nuxeo-elements pull request #594
Opened 2022-08-26 11:52 UTC by poonamyadav252

2022-08-29 08:09 UTC, rakeshkumar1019 requested changes
kindly follow the commit message standard.
for reference : https://github.com/nuxeo/nuxeo-elements/pull/577#pullrequestreview-1064886303
also kindly look  cross-repo check is failing.

2022-08-31 08:01 UTC, rakeshkumar1019 approved these changes
looks good to me 👏 .

2022-08-31 09:00 UTC, swarnadipa-dev approved these changes
Looks good

2022-09-02 06:45 UTC, GuruprasadAnk1996 approved these changes

2022-09-02 09:24 UTC, Gabez0r approved these changes

2022-09-06 10:19 UTC, merged