ELEMENTS-1513:prevent nuxeo-selectivity dropdown arrow from overlapping text
nuxeo/nuxeo-elements pull request #605
Opened 2022-10-10 07:09 UTC by Nishant0928

2022-10-10 07:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nuxeo/nuxeo-elements?pullRequest=605) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nuxeo/nuxeo-elements?pullRequest=605) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nuxeo/nuxeo-elements?pullRequest=605) it.</sub>

2022-10-11 05:00 UTC, rakeshkumar1019 requested changes
Commit Message Format:
`TicketNumber:<space><description starting with small letter>`
Here it will be 
`ELEMENTS-1513: prevent nuxeo-selectivity dropdown arrow from overlapping text`

2022-10-13 08:30 UTC, rakeshkumar1019 submitted a review, later dismissed

2022-10-21 07:44 UTC, poonamyadav252 reviewed
I am not able to see the changes in the second file, have you done changes in those files?

<img width="1143" alt="Screenshot 2022-10-21 at 1 11 33 PM" src="https://user-images.githubusercontent.com/109743453/197140859-fc48f3d2-ca49-42c5-9080-981a1138b22a.png">

2022-10-27 07:23 UTC, Nishant0928 commented
> I am not able to see the changes in the second file, have you done changes in those files?
> 
> <img alt="Screenshot 2022-10-21 at 1 11 33 PM" width="1143" src="https://user-images.githubusercontent.com/109743453/197140859-fc48f3d2-ca49-42c5-9080-981a1138b22a.png">

yes @poonamyadav252 ,The changes have been made only in one file i.e. data-table-cell.js

2022-10-28 14:28 UTC, closed without merging