ELEMENTS-1542: fixed flicker during scroll in search view
nuxeo/nuxeo-elements pull request #623
Opened 2022-11-30 02:18 UTC by swarnadipa-dev

2022-11-30 06:50 UTC, Nisha-QA approved these changes
Looks good

2022-11-30 06:56 UTC, GuruprasadAnk1996 approved these changes

2022-11-30 07:11 UTC, Nishant0928 approved these changes

2022-12-01 07:50 UTC, poonamyadav252 requested changes

2022-12-01 07:50 UTC, poonamyadav252 commented on ui/nuxeo-document-preview.js
> +        if (this.document.type.toLowerCase() === 'picture') {
can we write this line of code in a more optimized way?

2023-02-01 07:52 UTC, closed without merging