Elements 1544 distinguish view vs download in history tab
nuxeo/nuxeo-elements pull request #624
Opened 2022-11-30 09:40 UTC by swarnadipa-dev

2022-12-19 07:02 UTC, rakeshkumar1019 submitted a review, later dismissed

2022-12-19 08:10 UTC, satishyadav-dev approved these changes, later dismissed

2022-12-19 08:12 UTC, GuruprasadAnk1996 approved these changes, later dismissed

2022-12-19 08:12 UTC, Nishant0928 approved these changes, later dismissed

2022-12-20 08:59 UTC, Pranit-Sotre approved these changes, later dismissed
Looks good.

2022-12-20 10:43 UTC, Nishant0928 approved these changes, later dismissed

2022-12-20 10:46 UTC, GuruprasadAnk1996 approved these changes, later dismissed

2022-12-20 11:18 UTC, rakeshkumar1019 reviewed
Can we find anyway to remove the hardcoded values `clientReason=view` and `clientReason=download`? because if no one looks at the code, they will not realise that `clientReason` has two values(view/download).

2022-12-20 12:20 UTC, rajatgoel-gl commented on ui/nuxeo-document-preview.js
> +          return `${filteredViews[0].content.data}&clientReason=view`;
Kindly replace the hard coded repetition with the Generic functionality

2022-12-20 12:20 UTC, rajatgoel-gl commented on ui/nuxeo-document-preview.js
> +              data: `${conversion.content.data}&clientReason=view`,
Kindly replace the hard coded repetition with the Generic functionality

2022-12-20 12:20 UTC, rajatgoel-gl commented on ui/actions/nuxeo-download-button.js
> +      blob.data = `${blob.data.split('&clientReason')[0]}&clientReason=download`;
Kindly replace the hard coded repetition with the Generic functionality

2022-12-20 12:20 UTC, rajatgoel-gl commented on ui/nuxeo-video/nuxeo-video-conversions.js
> +                  <a href="[[conversion.content.data]]&clientReason=download">
Kindly replace the hard coded repetition with the Generic functionality

2022-12-23 04:26 UTC, GuruprasadAnk1996 submitted a review, later dismissed

2022-12-23 04:27 UTC, Nishant0928 approved these changes, later dismissed

2022-12-23 12:01 UTC, rajatgoel-gl commented on ui/nuxeo-document-preview.js
> +        }
Kindly optimize it and remove all repetitive code. 

Also this is a seperate logic; kindly have it in separate method for it.

2022-12-23 12:01 UTC, rajatgoel-gl commented on ui/test/resources/videoProperties.js
> +        downloadData: 'videoURL&clientReason=download',
It should not be hardcoded like this

2023-01-03 12:31 UTC, GuruprasadAnk1996 approved these changes, later dismissed

2023-01-03 12:33 UTC, Nishant0928 approved these changes, later dismissed

2023-01-04 05:12 UTC, rajatgoel-gl requested changes

2023-01-04 05:12 UTC, rajatgoel-gl commented on core/test/nuxeo-document.test.js
> +      document.setDocumentViewDownloadProp();
no need to have separate initialize of data and calling of setDocumentViewDownloadProp. Kindly merge with above data

2023-01-04 05:12 UTC, rajatgoel-gl commented on core/nuxeo-document.js
> +                  this.appendClientReason(prop.content);
Change this statements
if (prop.file) {
this.appendClientReason(prop.file);
} else {
this.appendClientReason(prop.content);
}
to below optimized code
this.appendClientReason(prop.file ? prop.file: prop.content);

2023-01-04 05:17 UTC, poonamyadav252 reviewed
Kindly consider the suggested changes.

2023-01-04 05:22 UTC, rajatgoel-gl requested changes

2023-01-04 05:22 UTC, rajatgoel-gl commented on ui/nuxeo-document-preview.js
> +              data: `${conversion.content.viewData}`,
Kindly change left side to viewData as well

2023-01-04 05:22 UTC, rajatgoel-gl commented on ui/nuxeo-document-preview.js
> +              data: this._blob.viewData,
Kindly change left side to viewData as well

2023-01-04 05:29 UTC, rajatgoel-gl requested changes

2023-01-04 05:29 UTC, rajatgoel-gl commented on core/test/nuxeo-document.test.js
> +          'file:content': {
'vid:transcodedVideos':  can also be part of this properties object

2023-01-04 07:19 UTC, Nishant0928 approved these changes

2023-01-04 07:20 UTC, rajatgoel-gl approved these changes

2023-01-04 07:31 UTC, rakeshkumar1019 approved these changes

2023-01-04 07:40 UTC, GuruprasadAnk1996 approved these changes

2023-01-04 07:50 UTC, satishyadav-dev approved these changes

2023-01-04 12:26 UTC, rakeshkumar1019 commented on ui/viewers/nuxeo-video-viewer.js
> +            controlsList="nodownload"
just for consistency can we make `noDownload`  here ?

2023-01-04 12:31 UTC, swarnadipa-dev commented on ui/viewers/nuxeo-video-viewer.js
> +            controlsList="nodownload"
it is a default HTML attribute value which spells like  this.

2023-01-04 12:34 UTC, rakeshkumar1019 commented on ui/viewers/nuxeo-video-viewer.js
> +            controlsList="nodownload"
Okay, thank you for informing me.

2023-02-01 04:51 UTC, closed without merging