ELEMENTS-1560: fix alignment of saved searches dropdown
nuxeo/nuxeo-elements pull request #641
Opened 2023-01-02 10:21 UTC by satishyadav-dev

ELEMENTS-1560: fix alignment of saved searches dropdown

2023-01-02 10:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nuxeo/nuxeo-elements?pullRequest=641) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nuxeo/nuxeo-elements?pullRequest=641) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nuxeo/nuxeo-elements?pullRequest=641) it.</sub>

2023-01-05 09:17 UTC, rakeshkumar1019 requested changes
Cross repo Check is failing, looks like its random one.kindly re-run the checks.
Also we use 1 commit per PR so kindly squash the commits.

2023-01-09 09:03 UTC, rakeshkumar1019 submitted a review, later dismissed
looks good, kindly confirm the changes with PO once before merging the code.

2023-01-09 09:08 UTC, GuruprasadAnk1996 submitted a review, later dismissed

2023-01-12 04:23 UTC, Nishant0928 submitted a review, later dismissed

2023-01-12 04:25 UTC, GuruprasadAnk1996 approved these changes, later dismissed

2023-01-12 10:57 UTC, Nishant0928 approved these changes

2023-01-12 10:59 UTC, rakeshkumar1019 approved these changes

2023-01-12 11:26 UTC, GuruprasadAnk1996 approved these changes

2023-01-13 04:41 UTC, rajatgoel-gl approved these changes

2023-01-13 05:11 UTC, merged