ELEMENTS-1569: enable clear button on nuxeo date picker
nuxeo/nuxeo-elements pull request #668
Opened 2023-02-07 07:41 UTC by Nishant0928

https://jira.nuxeo.com/browse/ELEMENTS-1569

2023-02-07 10:09 UTC, rakeshkumar1019 submitted a review, later dismissed

2023-02-07 10:54 UTC, swarnadipa-dev submitted a review, later dismissed

2023-02-07 20:26 UTC, tomcat114 commented
Before merging, the ticket states that this should be settable on the element. For ELEMENTS-1570, this configuration should be passed to the nuxeo-date-picker element so that the developer can configure what fields are allowed to be cleared.

2023-02-09 04:43 UTC, rajatgoel-gl approved these changes, later dismissed

2023-02-28 06:19 UTC, GuruprasadAnk1996 approved these changes, later dismissed

2023-02-28 06:23 UTC, rakeshkumar1019 approved these changes

2023-02-28 06:28 UTC, rakeshkumar1019 approved these changes, later dismissed

2023-02-28 07:08 UTC, Pranit-Sotre approved these changes, later dismissed

2023-02-28 07:46 UTC, satishyadav-dev submitted a review, later dismissed

2023-02-28 08:23 UTC, rajatgoel-gl approved these changes, later dismissed

2023-02-28 09:51 UTC, bchauvin requested changes, later dismissed
Suggested label change

2023-02-28 09:51 UTC, bchauvin commented on ui/widgets/nuxeo-date-picker.js
> +         * Check this box to remove clear button from nuxeo-date-picker.
```suggestion
         * Enable this property to remove the button allowing a user to clear the date currently set. Button is present by default.
```

2023-02-28 12:20 UTC, satishyadav-dev approved these changes

2023-02-28 12:21 UTC, rakeshkumar1019 approved these changes

2023-02-28 12:21 UTC, rajatgoel-gl approved these changes

2023-02-28 12:31 UTC, GuruprasadAnk1996 approved these changes

2023-02-28 13:27 UTC, merged