ELEMENTS-1580: fix tool tip not disappearing
nuxeo/nuxeo-elements pull request #680
Opened 2023-02-27 20:01 UTC by satishyadav-dev

https://jira.nuxeo.com/browse/ELEMENTS-1580

2023-03-01 06:13 UTC, Nishant0928 submitted a review, later dismissed

2023-03-01 06:14 UTC, GuruprasadAnk1996 approved these changes, later dismissed

2023-03-01 06:19 UTC, rakeshkumar1019 submitted a review, later dismissed

2023-03-01 10:33 UTC, rajatgoel-gl requested changes

2023-03-01 10:33 UTC, rajatgoel-gl commented on ui/widgets/nuxeo-tooltip.js
> +      const paperToolTip = document.getElementsByTagName('paper-tooltip');
Kindly dont change the old code instead add below code above old code

     if (this._tooltip == undefined && document.getElementsByTagName('paper-tooltip') && document.getElementsByTagName('paper-tooltip')[0]) {
        this._tooltip =document.getElementsByTagName('paper-tooltip')[0];
     }

2023-03-02 10:23 UTC, Nishant0928 approved these changes

2023-03-02 10:23 UTC, GuruprasadAnk1996 approved these changes

2023-03-02 10:23 UTC, rakeshkumar1019 approved these changes

2023-03-02 10:26 UTC, rajatgoel-gl approved these changes

2023-03-02 10:28 UTC, merged