ELEMENTS-1597:FORWARD PORT: fix preview fails to load when downloadin…
nuxeo/nuxeo-elements pull request #707
Opened 2023-04-17 08:29 UTC by swarnadipa-dev

…g document

2023-04-17 11:03 UTC, rakeshkumar1019 approved these changes

2023-04-17 11:04 UTC, Nishant0928 approved these changes

2023-04-17 11:04 UTC, GuruprasadAnk1996 approved these changes

2023-04-17 14:01 UTC, rajatgoel-gl requested changes

2023-04-17 14:01 UTC, rajatgoel-gl commented on ui/actions/nuxeo-download-button.js
> +          window.location.href = blob.downloadUrl ? blob.downloadUrl : blob.data;
Repetitive code

2023-04-18 04:36 UTC, rajatgoel-gl approved these changes

2023-04-18 04:53 UTC, merged