ELEMENTS-1593: FORWARD PORT: fix nuxeo-selectivity
nuxeo/nuxeo-elements pull request #745
Opened 2023-05-16 08:59 UTC by poonamyadav252

2023-05-17 04:31 UTC, Nishant0928 approved these changes, later dismissed

2023-05-18 06:38 UTC, swarnadipa-dev approved these changes, later dismissed

2023-05-18 06:42 UTC, rahuljain-dev approved these changes, later dismissed

2023-05-18 10:01 UTC, rajatgoel-gl requested changes

2023-05-18 10:01 UTC, rajatgoel-gl commented on ui/widgets/nuxeo-selectivity.js
> +            resultsHtml = this.selectivity.template('noResults', { term: options.term });
This is a repetition of line 2440 & 2441. Kindly remove repetitive code.

2023-05-18 10:01 UTC, poonamyadav252 commented on ui/widgets/nuxeo-selectivity.js
> +            resultsHtml = this.selectivity.template('noResults', { term: options.term });
yes, this needs to be changed.

2023-05-18 10:04 UTC, poonamyadav252 commented on ui/widgets/nuxeo-selectivity.js
> +            resultsHtml = this.selectivity.template('noResults', { term: options.term });
once their parent PR #741  is approved then I will change it.

2023-05-19 05:23 UTC, rahuljain-dev approved these changes

2023-05-19 05:40 UTC, swarnadipa-dev approved these changes

2023-05-19 05:40 UTC, swarnadipa-dev approved these changes

2023-05-19 07:10 UTC, rajatgoel-gl approved these changes

2023-05-19 07:10 UTC, merged