ELEMENTS-1713: Fix nuxeo-directory-radio-group in Edit mode
nuxeo/nuxeo-elements pull request #878
Opened 2024-02-14 07:35 UTC by alokhyland

2024-02-14 09:36 UTC, swarnadipa-dev submitted a review, later dismissed

2024-02-22 10:21 UTC, madhurkulshrestha-hyland requested changes
Remove additional check for length. That is not required.

2024-02-23 11:40 UTC, madhurkulshrestha-hyland approved these changes

2024-02-27 06:43 UTC, Nishant0928 approved these changes

2024-02-27 07:24 UTC, swarnadipa-dev approved these changes

2024-03-06 06:22 UTC, merged