ELEMENTS 1721: Backport fix rendering of newly added tag when tag san…
nuxeo/nuxeo-elements pull request #891
Opened 2024-02-27 11:06 UTC by Nishant0928

…itization is enabled on the server side

2024-02-28 06:28 UTC, alokhyland approved these changes, later dismissed

2024-02-29 06:40 UTC, swarnadipa-dev submitted a review, later dismissed

2024-03-07 06:13 UTC, madhurkulshrestha-hyland requested changes, later dismissed

2024-03-07 06:13 UTC, madhurkulshrestha-hyland commented on ui/widgets/nuxeo-tag-suggestion.js
> +          const lenArr = response.properties['nxtag:tags'].length;
add null checks on response and response.properties['nxtag:tags'] using optional chaining operator

2024-03-07 06:13 UTC, madhurkulshrestha-hyland commented on ui/widgets/nuxeo-tag-suggestion.js
> +          const { label } = response.properties['nxtag:tags'][lenArr - 1];
what happens if response.properties['nxtag:tags'] is empty array. In that case this line will throw an exception. Add safe checks

2024-03-12 04:26 UTC, swarnadipa-dev approved these changes

2024-03-12 04:27 UTC, alokhyland approved these changes

2024-03-12 05:36 UTC, madhurkulshrestha-hyland approved these changes

2024-03-12 05:56 UTC, merged