ELEMENTS-1731: Fix display of long username under activity section
nuxeo/nuxeo-elements pull request #896
Opened 2024-03-27 10:24 UTC by alokhyland

2024-04-01 10:06 UTC, madhurkulshrestha-hyland approved these changes, later dismissed

2024-04-01 10:08 UTC, swarnadipa-dev submitted a review, later dismissed

2024-04-01 11:35 UTC, Nishant0928 approved these changes, later dismissed

2024-04-04 04:58 UTC, swarnadipa-dev approved these changes, later dismissed

2024-04-04 06:53 UTC, Nishant0928 approved these changes, later dismissed

2024-04-04 06:55 UTC, madhurkulshrestha-hyland requested changes

2024-04-04 06:55 UTC, madhurkulshrestha-hyland commented on ui/widgets/nuxeo-user-avatar.js
> +          .user-inital {
rectify spelling of initial

2024-04-04 11:25 UTC, madhurkulshrestha-hyland approved these changes, later dismissed

2024-04-05 05:29 UTC, swarnadipa-dev submitted a review, later dismissed

2024-05-08 11:06 UTC, closed without merging