ELEMENTS-1731: fix display of long username under activity section
nuxeo/nuxeo-elements pull request #908
Opened 2024-04-28 06:36 UTC by alokhyland

2024-04-29 07:07 UTC, madhurkulshrestha-hyland requested changes

2024-04-29 07:07 UTC, madhurkulshrestha-hyland commented on ui/widgets/nuxeo-user-tag.js
> +        const toatlAvatarWidth = userAvatar.length * userAvatarWidth;
rectify spelling

2024-05-09 04:36 UTC, alokhyland commented on ui/widgets/nuxeo-user-tag.js
> +        const toatlAvatarWidth = userAvatar.length * userAvatarWidth;
done

2024-05-09 05:51 UTC, rakeshkumar1019 approved these changes
Approving based solely on the belief that these are static elements and haven't been dynamically configured through Nuxeo Studio, as we're altering the data type to an array.

2024-05-09 06:13 UTC, Nishant0928 approved these changes

2024-05-09 06:18 UTC, madhurkulshrestha-hyland approved these changes

2024-05-17 04:24 UTC, merged