WEBUI-1504: Tags fix mixed case entry
nuxeo/nuxeo-elements pull request #958
Opened 2024-10-14 03:38 UTC by rahuljain-dev

https://jira.nuxeo.com/browse/WEBUI-1504

2024-10-15 06:59 UTC, rakeshkumar1019 approved these changes

2024-10-15 07:10 UTC, swarnadipa-dev approved these changes

2024-10-15 07:24 UTC, madhurkulshrestha-hyland requested changes

2024-10-15 07:24 UTC, madhurkulshrestha-hyland commented on ui/widgets/nuxeo-selectivity.js
> +          } else if (value && Array.isArray(value) && value.includes(options.term.toLowerCase())) {
add null check for options.term using ?

2024-10-15 07:24 UTC, madhurkulshrestha-hyland commented on ui/widgets/nuxeo-tag-suggestion.js
> +      term = term.toLowerCase();
add null check for term using ?

2024-10-16 05:53 UTC, madhurkulshrestha-hyland approved these changes

2024-11-06 07:53 UTC, closed without merging